import java.util.List;
import java.util.Map;

/**

 * Four changes from the baseline:
 *
 * 1. Receives List&lt;Reviewer&gt; from ReviewerManager — no longer instantiates
 *    Reviewer objects directly (GRASP Creator fix).
 *
 * 2. Single loop: assignReview() and submitReviewScore() called together for
 *    each reviewer in one pass, eliminating the dual-traversal of the baseline.
 *
 * 3. calculateAverage() and checkConsensus() removed — these are now owned
 *    entirely by EvaluationManager.applyRules(). The controller calls only
 *    startEvaluation() and applyRules(), reducing its interactions from 6
 *    evaluation-related calls to 2.
 *
 * 4. Passes submitting author to ReviewerManager before filtering so that
 *    conflict checking works correctly.
 *
 * Addresses: Task 2 issues — redundant calls, dual loop, Creator violation,
 *            SubmissionController overloaded with responsibilities.
 */
public class SubmissionController {

    private Validator       validator;
    private Database        database;
    private ReviewerManager reviewerManager;
    private EvaluationManager evaluationManager;

    public SubmissionController(Validator validator, Database database,
                                ReviewerManager reviewerManager,
                                EvaluationManager evaluationManager) {
        this.validator         = validator;
        this.database          = database;
        this.reviewerManager   = reviewerManager;
        this.evaluationManager = evaluationManager;
    }

    public String submit(Map<String, Object> data) {

        // [alt: invalid] — validateFormat(data) → valid/invalid
        if (!validator.validateFormat(data)) {
            return "error";
        }

        // [valid] — saveSubmission(data) → confirmation
        String confirmation = database.saveSubmission(data);
        System.out.println("SubmissionController: DB confirmed save → " + confirmation);

        // Pass author to ReviewerManager before filtering (for conflict check)
        String author = data.getOrDefault("author", "").toString();
        reviewerManager.setSubmissionAuthor(author);

        // getAvailableReviewers() → List<Reviewer> (objects, not strings)
        List<Reviewer> reviewers = reviewerManager.getAvailableReviewers();

        // startEvaluation()
        evaluationManager.startEvaluation();

        // [loop: each reviewer — single pass] (OPTIMISED)
        // assignReview() and submitReviewScore() in one iteration.
        // Score is generated by the Reviewer itself — no hardcoded value here.
        for (Reviewer reviewer : reviewers) {
            reviewer.assignReview();
            reviewer.submitReviewScore(evaluationManager);
            reviewerManager.incrementWorkload(reviewer.getName());
        }

        // applyRules() — owns the full evaluation pipeline (OPTIMISED)
        // calculateAverage() and checkConsensus() are called internally
        evaluationManager.applyRules();

        return "success";
    }
}